{"uuid": "12566f09-2611-4ac5-9aef-4bba5c67a9c7", "children": ["27151689-82fc-487e-b724-8d5ffb45b854", "66bb8f5b-061c-4a7a-a53c-c1a19707dcf4"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='172.17.170.49', port=80): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DFBC129548>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))\n", "trace": "  File \"D:\\LearnProject\\SeleniumProject\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\LearnProject\\SeleniumProject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\LearnProject\\SeleniumProject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\LearnProject\\TestProject\\testcase\\conftest.py\", line 35, in browser\n    yield get_driver()\n  File \"D:\\LearnProject\\TestProject\\testcase\\conftest.py\", line 24, in get_driver\n    driver = webdriver.Remote('http://172.17.170.49/wd/hub')\n  File \"D:\\LearnProject\\SeleniumProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"D:\\LearnProject\\SeleniumProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"D:\\LearnProject\\SeleniumProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 319, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"D:\\LearnProject\\SeleniumProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 374, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"D:\\LearnProject\\SeleniumProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 402, in _request\n    resp = http.request(method, url, body=body, headers=headers)\n  File \"D:\\LearnProject\\SeleniumProject\\venv\\lib\\site-packages\\urllib3\\request.py\", line 79, in request\n    method, url, fields=fields, headers=headers, **urlopen_kw\n  File \"D:\\LearnProject\\SeleniumProject\\venv\\lib\\site-packages\\urllib3\\request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"D:\\LearnProject\\SeleniumProject\\venv\\lib\\site-packages\\urllib3\\poolmanager.py\", line 375, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"D:\\LearnProject\\SeleniumProject\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 796, in urlopen\n    **response_kw\n  File \"D:\\LearnProject\\SeleniumProject\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 796, in urlopen\n    **response_kw\n  File \"D:\\LearnProject\\SeleniumProject\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 796, in urlopen\n    **response_kw\n  File \"D:\\LearnProject\\SeleniumProject\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 756, in urlopen\n    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n  File \"D:\\LearnProject\\SeleniumProject\\venv\\lib\\site-packages\\urllib3\\util\\retry.py\", line 574, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1619704626284, "stop": 1619704635985}], "start": 1619704626284, "stop": 1619704636563}